name: Open Issue Message
on:
    issues:
       types: [opened]
jobs:
    auto_comment:
        runs-on: ubuntu-latest
        steps:
        - name: Harden Runner
          uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
          with:
            egress-policy: audit

        - uses: aws-actions/closed-issue-message@36b7048ea77bb834d16e7a7c5b5471ac767a4ca1 # v1
          with:
            # These inputs are both required
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
            message: |
                     ### ⚠️DEPRECATION NOTICE⚠️ 
                     This package is no longer maintained and has been replaced by [`boto3`](https://github.com/boto/boto3/). Issues are not triaged or reviewed by AWS. The issues in this repository can be used by the community for support purposes. If you are having an issue with the [`boto3`](https://github.com/boto/boto3/) package or the [AWS CLI](https://github.com/aws/aws-cli/), please open an issue on their respective repositories.
